import { Inter, Nabla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Nabvar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
          <link rel="icon" href="/icons/icon-192x192.png" />
          <meta name="theme-color" content="#000000" />
      </head>
      <body className={inter.className}>
        <Navbar />
        <main className="container mx-auto px-5 mt-4">
        {children}
        </main>
      </body>
    </html>
  );
}
